### ISSUE TITLE
Source Maps Not Generated

### ISSUE THREAD

**Issue by victormoukhortov** [webpack-contrib/expose-loader#18]
It seems as though source maps for my exposed file don't get generated properly:

``` javascript
loaders: [{
   test: require.resolve('./index.js'),
   loaders: ['expose?MyProject', 'babel-loader']
}]
```

The generated source map looks like this (using cheap-module-eval-source-map), which does not match the contents of `index.js`

``` javascript
module.exports = global["MyProject"] = require("-!/{...}/node_modules/babel-loader/index.js!/{...}/index.js");

/** WEBPACK FOOTER **
 ** index.js
 **/
```

**Comment by evisong** [comment]
Facing the same issue. Source map is not correct.

**Comment by evisong** [comment]
I've met another related issue: with the combination of `cheap-module-eval-source-map` and `babel?presets[]=es2015&presets[]=react&presets[]=stage-0`, the build failed due to soft errors:
```
... Cannot assign to read only property \'mappings\' of {"version":3,"sources":["... 
```
Which seems that expose-loader was trying to parse source maps but failed. 

My workaround is to switch the order of `expose-loader` and `babel-loader`: 
```javascript
loaders: ['babel?presets[]=es2015&presets[]=react&presets[]=stage-0', 'expose?xxx']
```

The generated source map is still not right (just like the one @victormoukhortov pasted), but at least the compilation succeeds.

**Comment by evisong** [comment]
Hi, team, 

Sorry for pushing but any progress on this ticket? 

Thanks.

**Comment by SpaceK33z** [comment]
@evisong no. Please try to create a PR if you really want this.
