### ISSUE TITLE
Clarify/improve config usages in readme 

### ISSUE THREAD

**Issue by WiseBird** [webpack-contrib/expose-loader#60]
Readme suggests `require.resolve` as a way to get path to a module, but webpack's resolution differs from node's one (e.g. webpack [supports](https://github.com/webpack/webpack/issues/1979) `module` property).

Please update readme with info about how to properly get module path.

**Comment by aramgre** [comment]
Is there a straightforward way to resolve the path to the module from the package name? I'm using something like `require.resolve('some-package/full/path/to/esm.js')` but this is fragile against the package authors changing the directory structure, for example.

It seems difficult because the final webpack `resolve.mainFields` might not be known when the expose-loader is configured.

**Comment by evilebottnawi** [comment]
Changing public structure of package is a breaking change and should be done only for major releases, other improvements done in master, feel free to open a new issues if you still have a problems with docs, we will improve it
